apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: game-pod
  template:
    metadata:
      labels:
        app: game-pod
    spec:
      containers:
      - name: game-container
        image: amrtarek6/connect4:1.0
        ports:
        - containerPort: 80
